#!/bin/sh
CURRENT=$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' index.html | head -1)
if [ -z "$CURRENT" ]; then exit 0; fi
MAJOR=$(echo "$CURRENT" | cut -d. -f1 | tr -d 'v')
MINOR=$(echo "$CURRENT" | cut -d. -f2)
PATCH=$(echo "$CURRENT" | cut -d. -f3)
NEW="v$MAJOR.$MINOR.$((PATCH + 1))"
sed -i "s/$CURRENT/$NEW/" index.html
git add index.html
echo "Version bumped: $CURRENT -> $NEW"
